services:
  backend-php:
    container_name: backend
    build: .
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - PHP_DATE_TIMEZONE="America/Sao_Paulo"
